namespace Lumi.Lexer;

/// <summary>
/// Specifies the kinds of tokens that can be recognized during lexical analysis of source code.
/// </summary>
public enum TokenKind
{
    Eof,
    Identifier,
    Keyword,
    Number,
    String,
    Comment,
    Boolean,
    Null,
    Undefined,
    LeftParen,
    RightParen,
    LeftBrace,
    RightBrace,
    LeftBracket,
    RightBracket,
    Dot,
    Semicolon,
    Comma,
    Colon,
    Question,
    Exclamation,
    Assign,
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    LessThan,
    GreaterThan,
    Equal,
    EqualEqual,
    NotEqual,
    LessThanEqual,
    GreaterThanEqual,
    PlusAssign,
    MinusAssign,
    Increment,
    Decrement,
    Arrow,
    LogicalAnd,
    LogicalOr,
}