<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lumi.Ast\Lumi.AST.csproj" />
    <ProjectReference Include="..\Lumi.Bytecode\Lumi.Bytecode.csproj" />
    <ProjectReference Include="..\Lumi.Parser\Lumi.Parser.csproj" />
    <ProjectReference Include="..\Lumi.SemanticAnalyzer\Lumi.SemanticAnalyzer.csproj" />
    <ProjectReference Include="..\Lumi.VM\Lumi.VM.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

</Project>
