using Lumi.Bytecode;
using Lumi.Bytecode.Constants;
using Lumi.Bytecode.Instructions;
using Lumi.VM.Heap;
namespace Lumi.VM;

/// <summary>
/// Represents a simple stack-based virtual machine capable of executing bytecode instructions generated by a compiler
/// or bytecode generator.
/// </summary>
public sealed class VirtualMachine
{
    private const int InitialVariableCapacity = 256;
    private const int MaxStackSize = 1024;

    // Evaluation stack, fixed-size array with top pointer.
    private readonly Value[] _stack = new Value[MaxStackSize];
    private int _stackTop;

    // Variable storage, fixed-size with count.
    private Value[] _variables = new Value[InitialVariableCapacity];
    private int _variableCount;

    // Heap for dynamically allocated objects (arrays, structs, strings, etc.).
    private readonly HeapManager _heap = new();

    private readonly Stack<CallFrame> _callStack = [];
    private IReadOnlyDictionary<string, int> _functionAddresses = new Dictionary<string, int>();
    private IReadOnlyDictionary<string, IReadOnlyList<string>> _structDefinitions = new Dictionary<string, IReadOnlyList<string>>();
    private IReadOnlyDictionary<string, IReadOnlyDictionary<string, int>> _structMethodAddresses = new Dictionary<string, IReadOnlyDictionary<string, int>>();
    private int _ip;
    private int _basePointer;
    private int _executedInstructionCount;

    /// <summary>
    /// Executes the provided bytecode by interpreting its instructions sequentially.
    /// </summary>
    /// <param name="bytecode">The bytecode to execute, containing the instructions and constants to be processed.</param>
    public void Execute(BytecodeResult bytecode)
    {
        var instructions = (List<Instruction>)bytecode.Instructions;
        var constants = (List<Constant>)bytecode.Constants;
        _functionAddresses = bytecode.FunctionAddresses;
        _structDefinitions = bytecode.StructDefinitions;
        _structMethodAddresses = bytecode.StructMethodAddresses;
        _ip = _executedInstructionCount;
        var instructionCount = instructions.Count;

        while (_ip < instructionCount)
        {
            var instruction = instructions[_ip];
            switch (instruction.Kind)
            {
                case InstructionKind.PushConst:
                    _stack[_stackTop++] = ConstantToValue(constants[instruction.IntOperand.GetValueOrDefault()]);
                    break;

                case InstructionKind.Add:
                    {
                        var b = _stack[--_stackTop];
                        var a = _stack[--_stackTop];

                        if (TryGetStringValue(a, out _) || TryGetStringValue(b, out _))
                        {
                            var handle = _heap.InternString(StringifyForConcatenation(a) + StringifyForConcatenation(b));
                            _stack[_stackTop++] = Value.FromHeapObject(handle);
                            break;
                        }
                        _stack[_stackTop++] = Value.FromNumber(a.Number + b.Number);
                        break;
                    }

                case InstructionKind.Sub:
                    {
                        var b = _stack[--_stackTop];
                        var a = _stack[--_stackTop];
                        _stack[_stackTop++] = Value.FromNumber(a.Number - b.Number);
                        break;
                    }

                case InstructionKind.Mul:
                    {
                        var b = _stack[--_stackTop];
                        var a = _stack[--_stackTop];
                        _stack[_stackTop++] = Value.FromNumber(a.Number * b.Number);
                        break;
                    }

                case InstructionKind.Div:
                    {
                        var b = _stack[--_stackTop];
                        var a = _stack[--_stackTop];
                        _stack[_stackTop++] = Value.FromNumber(a.Number / b.Number);
                        break;
                    }

                case InstructionKind.Mod:
                    {
                        var b = _stack[--_stackTop];
                        var a = _stack[--_stackTop];
                        _stack[_stackTop++] = Value.FromNumber(a.Number % b.Number);
                        break;
                    }

                case InstructionKind.StoreVar:
                    {
                        var slot = _basePointer + instruction.IntOperand.GetValueOrDefault();
                        if (slot >= _variables.Length)
                            GrowVariables(slot);
                        _variables[slot] = _stack[--_stackTop];
                        if (slot >= _variableCount)
                            _variableCount = slot + 1;
                        break;
                    }

                case InstructionKind.LoadPreludeGlobal:
                    {
                        AllocateHeapObject(new HeapNativeObject(instruction.GetSafeStringOperand(), []));
                        break;
                    }

                case InstructionKind.NewStruct:
                    {
                        var structName = instruction.GetSafeStringOperand();
                        var argumentCount = instruction.GetSafeIntOperand();

                        if (!_structDefinitions.TryGetValue(structName, out var fields))
                            throw VirtualMachineError.UndefinedStruct(structName);

                        if (argumentCount > fields.Count)
                            throw VirtualMachineError.StructConstructorArgumentCountMismatch(structName, fields.Count, argumentCount);

                        var args = new Value[argumentCount];
                        for (int i = argumentCount - 1; i >= 0; i--)
                        {
                            args[i] = _stack[--_stackTop];
                        }

                        var values = new Dictionary<string, Value>(StringComparer.Ordinal);
                        for (int i = 0; i < fields.Count; i++)
                        {
                            values[fields[i]] = i < args.Length ? args[i] : Value.Undefined();
                        }

                        AllocateHeapObject(new HeapStructObject(structName, values), values.Values);
                        break;
                    }

                case InstructionKind.LoadField:
                    {
                        var fieldName = instruction.GetSafeStringOperand();
                        var target = _stack[--_stackTop];

                        if (!target.IsHeapAllocated())
                            throw VirtualMachineError.FieldAccessTargetNotStruct(target.Kind);

                        var heapObject = _heap.Get<HeapObject>(target.GetRequiredHeapHandle());

                        if (heapObject is not HeapStructObject structObject || structObject.Fields is null)
                            throw VirtualMachineError.FieldAccessTargetNotStruct(heapObject.Kind);

                        if (!structObject.Fields.TryGetValue(fieldName, out var fieldValue))
                            throw VirtualMachineError.UnknownStructField(fieldName);

                        _stack[_stackTop++] = fieldValue;
                        break;
                    }

                case InstructionKind.StoreField:
                    {
                        var fieldName = instruction.GetSafeStringOperand();
                        var fieldValue = _stack[--_stackTop];
                        var target = _stack[--_stackTop];

                        if (!target.IsHeapAllocated())
                            throw VirtualMachineError.FieldAccessTargetNotStruct(target.Kind);

                        var heapObject = _heap.Get<HeapObject>(target.GetRequiredHeapHandle());

                        if (heapObject is not HeapStructObject structObject || structObject.Fields is null)
                            throw VirtualMachineError.FieldAccessTargetNotStruct(heapObject.Kind);

                        if (!structObject.Fields.ContainsKey(fieldName))
                            throw VirtualMachineError.UnknownStructField(fieldName);

                        structObject.Fields[fieldName] = fieldValue;
                        break;
                    }

                case InstructionKind.MakeArray:
                    {
                        var count = instruction.GetSafeIntOperand();
                        if (count < 0)
                            throw VirtualMachineError.InvalidArrayElementCount(count);

                        var values = new Value[count];
                        for (int i = count - 1; i >= 0; i--)
                        {
                            values[i] = _stack[--_stackTop];
                        }

                        AllocateHeapObject(new HeapArrayObject([.. values]));
                        break;
                    }

                case InstructionKind.IndexArray:
                    {
                        var index = (int)_stack[--_stackTop].Number;
                        var heapHandle = _stack[--_stackTop];

                        if (!heapHandle.IsHeapAllocated())
                            throw VirtualMachineError.IndexTargetNotArray(heapHandle.Kind);

                        var heapObject = _heap.Get<HeapObject>(heapHandle.GetRequiredHeapHandle());

                        if (heapObject is not HeapArrayObject arrayObject)
                            throw VirtualMachineError.IndexTargetNotArray(heapObject.Kind);

                        if (index < 0 || index >= arrayObject.Elements.Count)
                            throw VirtualMachineError.IndexOutOfRange(index, arrayObject.Elements.Count);

                        _stack[_stackTop++] = arrayObject.Elements[index];
                        break;
                    }

                case InstructionKind.LoadVar:
                    {
                        var slot = _basePointer + instruction.GetSafeIntOperand();
                        _stack[_stackTop++] = _variables[slot];
                        break;
                    }

                case InstructionKind.Lt:
                    {
                        var b = _stack[--_stackTop];
                        var a = _stack[--_stackTop];
                        _stack[_stackTop++] = Value.FromBoolean(a.Number < b.Number);
                        break;
                    }

                case InstructionKind.Gt:
                    {
                        var b = _stack[--_stackTop];
                        var a = _stack[--_stackTop];
                        _stack[_stackTop++] = Value.FromBoolean(a.Number > b.Number);
                        break;
                    }

                case InstructionKind.Leq:
                    {
                        var b = _stack[--_stackTop];
                        var a = _stack[--_stackTop];
                        _stack[_stackTop++] = Value.FromBoolean(a.Number <= b.Number);
                        break;
                    }

                case InstructionKind.Eq:
                    {
                        var b = _stack[--_stackTop];
                        var a = _stack[--_stackTop];
                        _stack[_stackTop++] = Value.FromBoolean(a.Number == b.Number);
                        break;
                    }

                case InstructionKind.Negate:
                    _stack[_stackTop - 1] = Value.FromNumber(-_stack[_stackTop - 1].Number);
                    break;

                case InstructionKind.Not:
                    _stack[_stackTop - 1] = Value.FromBoolean(!_stack[_stackTop - 1].Bool);
                    break;

                case InstructionKind.Jump:
                    _ip = instruction.GetSafeIntOperand();
                    continue;

                case InstructionKind.JumpIfFalse:
                    if (!_stack[--_stackTop].Bool)
                    {
                        _ip = instruction.GetSafeIntOperand();
                        continue;
                    }
                    break;

                case InstructionKind.JumpIfTrue:
                    if (_stack[--_stackTop].Bool)
                    {
                        _ip = instruction.GetSafeIntOperand();
                        continue;
                    }
                    break;

                case InstructionKind.CallFn:
                    {
                        var functionName = instruction.StringOperand!;
                        if (!_functionAddresses.TryGetValue(functionName, out var functionAddress))
                            throw VirtualMachineError.UndefinedFunction(functionName);

                        _callStack.Push(new CallFrame(ReturnAddress: _ip + 1, PreviousBasePointer: _basePointer));
                        _basePointer = _variableCount;
                        _ip = functionAddress;
                        continue;
                    }

                case InstructionKind.CallMemberMethod:
                    {
                        var methodName = instruction.GetSafeStringOperand();
                        var argumentCount = instruction.GetSafeIntOperand();
                        var receiverIndex = _stackTop - argumentCount - 1;
                        var target = _stack[receiverIndex];
                        var heapObject = _heap.Get<HeapObject>(target.GetRequiredHeapHandle());

                        if (heapObject is HeapArrayObject)
                        {
                            var args = new Value[argumentCount];
                            for (int i = argumentCount - 1; i >= 0; i--)
                            {
                                args[i] = _stack[--_stackTop];
                            }

                            target = _stack[--_stackTop];
                            var heapHandle = target.GetRequiredHeapHandle();
                            heapObject = _heap.Get<HeapObject>(heapHandle);

                            _stack[_stackTop++] = NativeMemberDispatcher.Invoke(_heap, target, methodName, args);
                            break;
                        }

                        if (heapObject is HeapStructObject heapStructObject)
                        {
                            if (heapStructObject.StructName is null
                                || !_structMethodAddresses.TryGetValue(heapStructObject.StructName, out var methods)
                                || !methods.TryGetValue(methodName, out var methodAddress))
                            {
                                throw VirtualMachineError.UnknownStructMethod(heapStructObject.StructName ?? "struct", methodName);
                            }

                            _callStack.Push(new CallFrame(ReturnAddress: _ip + 1, PreviousBasePointer: _basePointer));
                            _basePointer = _variableCount;
                            _ip = methodAddress;

                            continue;
                        }

                        if (heapObject is HeapNativeObject)
                        {
                            var args = new Value[argumentCount];

                            for (int i = argumentCount - 1; i >= 0; i--)
                            {
                                args[i] = _stack[--_stackTop];
                            }

                            target = _stack[--_stackTop];
                            heapObject = _heap.Get<HeapObject>(target.GetRequiredHeapHandle()); // heapobject ValueKind is number?

                            _stack[_stackTop++] = NativeMemberDispatcher.Invoke(_heap, target, methodName, args);
                            break;
                        }

                        throw VirtualMachineError.MethodTargetNotSupported(methodName, target.Kind);
                    }

                case InstructionKind.Return:
                    {
                        if (_callStack.Count == 0)
                            throw VirtualMachineError.ReturnWithoutCall();

                        var returnValue = _stack[--_stackTop];
                        var frame = _callStack.Pop();

                        _variableCount = _basePointer;
                        _basePointer = frame.PreviousBasePointer;

                        _stack[_stackTop++] = returnValue;
                        _ip = frame.ReturnAddress;
                        continue;
                    }

                case InstructionKind.Pop:
                    _stackTop--;
                    break;

                case InstructionKind.Print:
                    {
                        var result = _stack[--_stackTop];
                        if (result.Kind == ValueKind.HeapObject)
                        {
                            var heapObject = _heap.Get<HeapObject>(result.GetRequiredHeapHandle());
                            Console.WriteLine(heapObject.PrintValue());
                        }
                        else
                        {
                            Console.WriteLine(result.PrintValue());
                        }
                        break;
                    }
            }
            _ip += 1;
        }
        _executedInstructionCount = _ip;
    }

    private void GrowVariables(int requiredSlot)
    {
        var newSize = _variables.Length;

        while (newSize <= requiredSlot)
            newSize *= 2;

        Array.Resize(ref _variables, newSize);
    }

    private IEnumerable<Value> EnumerateRoots()
    {
        for (var i = 0; i < _stackTop; i++)
        {
            yield return _stack[i];
        }

        for (var i = 0; i < _variableCount; i++)
        {
            yield return _variables[i];
        }
    }

    private void AllocateHeapObject(HeapObject heapObject, IEnumerable<Value>? additionalRoots = null)
    {
        IEnumerable<Value> Roots()
        {
            foreach (var root in EnumerateRoots()) yield return root;
            if (additionalRoots is not null)
            {
                foreach (var root in additionalRoots) yield return root;
            }
        }

        _heap.MaybeCollect(Roots());
        _stack[_stackTop++] = Value.FromHeapObject(_heap.Allocate(heapObject));
    }

    private Value ConstantToValue(Constant constant) => constant.Kind switch
    {
        ConstantKind.String => Value.FromHeapObject(_heap.InternString(constant.String!)),
        _ => Value.ConstantToValue(constant),
    };

    private bool TryGetStringValue(Value value, out string text)
    {
        text = string.Empty;

        if (!value.IsHeapAllocated())
        {
            return false;
        }

        text = _heap.GetStringValue(value.GetRequiredHeapHandle());

        return true;
    }

    private string StringifyForConcatenation(Value value)
        => TryGetStringValue(value, out var text)
            ? text
            : value.IsHeapAllocated()
                ? _heap.GetStringValue(value.GetRequiredHeapHandle())
                : value.PrintValue();
}