using Lumi.Bytecode;
using Lumi.Bytecode.Constants;
using Lumi.Bytecode.Instructions;
namespace Lumi.VM;

/// <summary>
/// Represents a simple stack-based virtual machine capable of executing bytecode instructions generated by a compiler
/// or bytecode generator.
/// </summary>
public sealed class VirtualMachine
{
    private const int InitialVariableCapacity = 256;
    private const int MaxStackSize = 1024;

    // Evaluation stack, fixed-size array with top pointer.
    private readonly Value[] _stack = new Value[MaxStackSize];
    private int _stackTop;

    // Variable storage, fixed-size with count.
    private Value[] _variables = new Value[InitialVariableCapacity];
    private int _variableCount;

    private readonly Stack<CallFrame> _callStack = [];
    private IReadOnlyDictionary<string, int> _functionAddresses = new Dictionary<string, int>();
    private IReadOnlyDictionary<string, IReadOnlyList<string>> _structDefinitions = new Dictionary<string, IReadOnlyList<string>>();
    private IReadOnlyDictionary<string, IReadOnlyDictionary<string, int>> _structMethodAddresses = new Dictionary<string, IReadOnlyDictionary<string, int>>();
    private int _ip;
    private int _basePointer;
    private int _executedInstructionCount;

    /// <summary>
    /// Executes the provided bytecode by interpreting its instructions sequentially.
    /// </summary>
    /// <param name="bytecode">The bytecode to execute, containing the instructions and constants to be processed.</param>
    public void Execute(BytecodeResult bytecode)
    {
        var instructions = (List<Instruction>)bytecode.Instructions;
        var constants = (List<Constant>)bytecode.Constants;
        _functionAddresses = bytecode.FunctionAddresses;
        _structDefinitions = bytecode.StructDefinitions;
        _structMethodAddresses = bytecode.StructMethodAddresses;
        _ip = _executedInstructionCount;
        var instructionCount = instructions.Count;

        while (_ip < instructionCount)
        {
            var instruction = instructions[_ip];
            switch (instruction.Kind)
            {
                case InstructionKind.PushConst:
                    _stack[_stackTop++] = Value.ConstantToValue(constants[instruction.IntOperand.GetValueOrDefault()]);
                    break;

                case InstructionKind.Add:
                    {
                        var b = _stack[--_stackTop];
                        var a = _stack[--_stackTop];
                        _stack[_stackTop++] = Value.FromNumber(a.Number + b.Number);
                        break;
                    }

                case InstructionKind.Sub:
                    {
                        var b = _stack[--_stackTop];
                        var a = _stack[--_stackTop];
                        _stack[_stackTop++] = Value.FromNumber(a.Number - b.Number);
                        break;
                    }

                case InstructionKind.Mul:
                    {
                        var b = _stack[--_stackTop];
                        var a = _stack[--_stackTop];
                        _stack[_stackTop++] = Value.FromNumber(a.Number * b.Number);
                        break;
                    }

                case InstructionKind.Div:
                    {
                        var b = _stack[--_stackTop];
                        var a = _stack[--_stackTop];
                        _stack[_stackTop++] = Value.FromNumber(a.Number / b.Number);
                        break;
                    }

                case InstructionKind.Mod:
                    {
                        var b = _stack[--_stackTop];
                        var a = _stack[--_stackTop];
                        _stack[_stackTop++] = Value.FromNumber(a.Number % b.Number);
                        break;
                    }

                case InstructionKind.StoreVar:
                    {
                        var slot = _basePointer + instruction.IntOperand.GetValueOrDefault();
                        if (slot >= _variables.Length)
                            GrowVariables(slot);
                        _variables[slot] = _stack[--_stackTop];
                        if (slot >= _variableCount)
                            _variableCount = slot + 1;
                        break;
                    }

                case InstructionKind.LoadPreludeGlobal:
                    _stack[_stackTop++] = Value.FromNativeObject(instruction.GetSafeStringOperand());
                    break;

                case InstructionKind.NewStruct:
                    {
                        var structName = instruction.GetSafeStringOperand();
                        var argumentCount = instruction.GetSafeIntOperand();

                        if (!_structDefinitions.TryGetValue(structName, out var fields))
                            throw VirtualMachineError.UndefinedStruct(structName);

                        if (argumentCount > fields.Count)
                            throw VirtualMachineError.StructConstructorArgumentCountMismatch(structName, fields.Count, argumentCount);

                        var args = new Value[argumentCount];
                        for (int i = argumentCount - 1; i >= 0; i--)
                        {
                            args[i] = _stack[--_stackTop];
                        }

                        var values = new Dictionary<string, Value>(StringComparer.Ordinal);
                        for (int i = 0; i < fields.Count; i++)
                        {
                            values[fields[i]] = i < args.Length ? args[i] : Value.Undefined();
                        }

                        _stack[_stackTop++] = Value.FromStruct(structName, values);
                        break;
                    }

                case InstructionKind.LoadField:
                    {
                        var fieldName = instruction.GetSafeStringOperand();
                        var target = _stack[--_stackTop];

                        if (target.Kind != ValueKind.Struct || target.Struct is null)
                            throw VirtualMachineError.FieldAccessTargetNotStruct(target.Kind);

                        if (!target.Struct.TryGetValue(fieldName, out var fieldValue))
                            throw VirtualMachineError.UnknownStructField(fieldName);

                        _stack[_stackTop++] = fieldValue;
                        break;
                    }

                case InstructionKind.StoreField:
                    {
                        var fieldName = instruction.GetSafeStringOperand();
                        var fieldValue = _stack[--_stackTop];
                        var target = _stack[--_stackTop];

                        if (target.Kind != ValueKind.Struct || target.Struct is null)
                            throw VirtualMachineError.FieldAccessTargetNotStruct(target.Kind);

                        if (!target.Struct.ContainsKey(fieldName))
                            throw VirtualMachineError.UnknownStructField(fieldName);

                        target.Struct[fieldName] = fieldValue;
                        break;
                    }

                case InstructionKind.MakeArray:
                    {
                        var count = instruction.GetSafeIntOperand();
                        if (count < 0)
                            throw VirtualMachineError.InvalidArrayElementCount(count);

                        var values = new Value[count];
                        for (int i = count - 1; i >= 0; i--)
                        {
                            values[i] = _stack[--_stackTop];
                        }

                        _stack[_stackTop++] = Value.FromArray([.. values]);
                        break;
                    }

                case InstructionKind.IndexArray:
                    {
                        var index = (int)_stack[--_stackTop].Number;
                        var array = _stack[--_stackTop];

                        if (array.Kind != ValueKind.Array || array.Array is null)
                            throw VirtualMachineError.IndexTargetNotArray(array.Kind);

                        if (index < 0 || index >= array.Array.Count)
                            throw VirtualMachineError.IndexOutOfRange(index, array.Array.Count);

                        _stack[_stackTop++] = array.Array[index];
                        break;
                    }

                case InstructionKind.LoadVar:
                    {
                        var slot = _basePointer + instruction.GetSafeIntOperand();
                        _stack[_stackTop++] = _variables[slot];
                        break;
                    }

                case InstructionKind.Lt:
                    {
                        var b = _stack[--_stackTop];
                        var a = _stack[--_stackTop];
                        _stack[_stackTop++] = Value.FromBoolean(a.Number < b.Number);
                        break;
                    }

                case InstructionKind.Gt:
                    {
                        var b = _stack[--_stackTop];
                        var a = _stack[--_stackTop];
                        _stack[_stackTop++] = Value.FromBoolean(a.Number > b.Number);
                        break;
                    }

                case InstructionKind.Leq:
                    {
                        var b = _stack[--_stackTop];
                        var a = _stack[--_stackTop];
                        _stack[_stackTop++] = Value.FromBoolean(a.Number <= b.Number);
                        break;
                    }

                case InstructionKind.Eq:
                    {
                        var b = _stack[--_stackTop];
                        var a = _stack[--_stackTop];
                        _stack[_stackTop++] = Value.FromBoolean(a.Number == b.Number);
                        break;
                    }

                case InstructionKind.Negate:
                    _stack[_stackTop - 1] = Value.FromNumber(-_stack[_stackTop - 1].Number);
                    break;

                case InstructionKind.Not:
                    _stack[_stackTop - 1] = Value.FromBoolean(!_stack[_stackTop - 1].Bool);
                    break;

                case InstructionKind.Jump:
                    _ip = instruction.GetSafeIntOperand();
                    continue;

                case InstructionKind.JumpIfFalse:
                    if (!_stack[--_stackTop].Bool)
                    {
                        _ip = instruction.GetSafeIntOperand();
                        continue;
                    }
                    break;

                case InstructionKind.JumpIfTrue:
                    if (_stack[--_stackTop].Bool)
                    {
                        _ip = instruction.GetSafeIntOperand();
                        continue;
                    }
                    break;

                case InstructionKind.CallFn:
                    {
                        var functionName = instruction.StringOperand!;
                        if (!_functionAddresses.TryGetValue(functionName, out var functionAddress))
                            throw VirtualMachineError.UndefinedFunction(functionName);

                        _callStack.Push(new CallFrame(ReturnAddress: _ip + 1, PreviousBasePointer: _basePointer));
                        _basePointer = _variableCount;
                        _ip = functionAddress;
                        continue;
                    }

                case InstructionKind.CallMemberMethod:
                    {
                        var methodName = instruction.GetSafeStringOperand();
                        var argumentCount = instruction.GetSafeIntOperand();
                        var receiverIndex = _stackTop - argumentCount - 1;
                        var target = _stack[receiverIndex];

                        // NOTE: move this to switch statement and cleaner approach for the ListMethods section
                        if (target.Kind == ValueKind.Struct)
                        {
                            if (target.StructName is null
                                || !_structMethodAddresses.TryGetValue(target.StructName, out var methods)
                                || !methods.TryGetValue(methodName, out var methodAddress))
                            {
                                throw VirtualMachineError.UnknownStructMethod(target.StructName ?? "struct", methodName);
                            }

                            _callStack.Push(new CallFrame(ReturnAddress: _ip + 1, PreviousBasePointer: _basePointer));
                            _basePointer = _variableCount;
                            _ip = methodAddress;

                            continue;
                        }

                        if (target.Kind == ValueKind.Array || target.Kind == ValueKind.NativeObject)
                        {
                            var args = new Value[argumentCount];
                            for (int i = argumentCount - 1; i >= 0; i--)
                            {
                                args[i] = _stack[--_stackTop];
                            }

                            target = _stack[--_stackTop];
                            _stack[_stackTop++] = NativeMemberDispatcher.Invoke(target, methodName, args);
                            break;
                        }

                        throw VirtualMachineError.MethodTargetNotSupported(methodName, target.Kind);
                    }

                case InstructionKind.Return:
                    {
                        if (_callStack.Count == 0)
                            throw VirtualMachineError.ReturnWithoutCall();

                        var returnValue = _stack[--_stackTop];
                        var frame = _callStack.Pop();

                        _variableCount = _basePointer;
                        _basePointer = frame.PreviousBasePointer;

                        _stack[_stackTop++] = returnValue;
                        _ip = frame.ReturnAddress;
                        continue;
                    }

                case InstructionKind.Pop:
                    _stackTop--;
                    break;

                case InstructionKind.Print:
                    Console.WriteLine(_stack[--_stackTop].PrintValue());
                    break;
            }
            _ip += 1;
        }
        _executedInstructionCount = _ip;
    }

    private void GrowVariables(int requiredSlot)
    {
        var newSize = _variables.Length;

        while (newSize <= requiredSlot)
            newSize *= 2;

        Array.Resize(ref _variables, newSize);
    }
}
