<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lumi.Bytecode\Lumi.Bytecode.csproj" />
    <ProjectReference Include="..\Lumi.Parser\Lumi.Parser.csproj" />
    <ProjectReference Include="..\Lumi.SemanticAnalyzer\Lumi.SemanticAnalyzer.csproj" />
    <ProjectReference Include="..\Lumi.VM\Lumi.VM.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\Examples\**\*.*" LinkBase="Examples" />
  </ItemGroup>

</Project>
