using Lumi.Ast;
using Lumi.Bytecode.Constants;
using Lumi.Bytecode.Instructions;
using Lumi.Bytecode.Locals;

namespace Lumi.Bytecode;

/// <summary>
/// Generates bytecode instructions and manages constants for a given abstract syntax tree (AST).
/// </summary>
public sealed class BytecodeGenerator
{
    private readonly List<Instruction> _instructions = new(capacity: 64);
    private readonly ConstantPool _constantPool = new();
    private readonly Dictionary<Label, List<int>> _unpatchedJumps = [];
    private readonly LocalManager _locals = new();
    private int _nextLabelId = 0;

    public IReadOnlyList<Instruction> Instructions => _instructions;
    public IReadOnlyList<Constant> Constants => _constantPool.Values;
    public IReadOnlyList<Local> Locals => _locals.AllLocals;

    public BytecodeGenerator()
    {
        _locals.EnterScope();
    }

    /// <summary>
    /// Generates a bytecode result by traversing the specified syntax node.
    /// </summary>
    /// <param name="node">The root node of the syntax tree to generate bytecode from. Cannot be null.</param>
    /// <returns>A <see cref="BytecodeResult"/> containing the generated bytecode for the provided syntax node.</returns>
    public BytecodeResult Generate(Node node)
    {
        Visit(node);

        return BytecodeResult.FromGenerator(this);
    }

    private void Visit(Node node)
    {
        switch (node)
        {
            case Program program:
                for (int i = 0; i < program.Body.Count; i++)
                    Visit(program.Body[i]);
                break;

            case BlockStatement block:
                _locals.EnterScope();
                foreach (var stmt in block.Body)
                    Visit(stmt);
                _locals.ExitScope();
                break;

            case VariableDeclaration variableDeclaration:
                VisitVariableDeclaration(variableDeclaration);
                break;

            case IdentifierNode identifier:
                var local = _locals.LookupLocal(identifier.Name) ?? throw BytecodeError.UndefinedVariable(identifier.Name);
                Emit(new Instruction(InstructionKind.LoadVar, intOperand: local.Label.Id));
                break;

            case PrintStatement printStatement:
                Visit(printStatement.Argument);
                Emit(new Instruction(InstructionKind.Print));
                break;

            case IfStatement ifStatement:
                VisitIfStatement(ifStatement);
                break;

            case ForStatement forStatement:
                VisitForStatement(forStatement);
                break;

            case NumberNode number:
                Emit(new Instruction(InstructionKind.PushConst, intOperand: AddConstant(Constant.FromNumber(number.Value))));
                break;

            case BooleanNode boolean:
                Emit(new Instruction(InstructionKind.PushConst, intOperand: AddConstant(Constant.FromBoolean(boolean.Value))));
                break;

            case StringNode str:
                Emit(new Instruction(InstructionKind.PushConst, intOperand: AddConstant(Constant.FromString(str.Value))));
                break;

            case ExpressionStatement expressionStatement:
                Visit(expressionStatement.Expression);
                break;

            case BinaryExpression binaryExpression:
                VisitBinaryExpression(binaryExpression);
                break;
        }
    }

    /// <summary>Allocates a fresh jump label whose target will be resolved later via <see cref="PatchLabel"/>.</summary>
    private Label NewLabel() => new(_nextLabelId++);

    /// <summary>Emits an unconditional jump to <paramref name="target"/>, recording it for back-patching.</summary>
    private void EmitJump(Label target)
    {
        _unpatchedJumps.TryAdd(target, []);
        _unpatchedJumps[target].Add(_instructions.Count);
        Emit(new Instruction(InstructionKind.Jump, intOperand: 0));
    }

    /// <summary>Emits a conditional jump that jumps to <paramref name="target"/> when the top-of-stack is false.</summary>
    private void EmitJumpIfFalse(Label target)
    {
        _unpatchedJumps.TryAdd(target, []);
        _unpatchedJumps[target].Add(_instructions.Count);
        Emit(new Instruction(InstructionKind.JumpIfFalse, intOperand: 0));
    }

    /// <summary>
    /// Resolves all jumps that target <paramref name="label"/> to point at the current instruction position,
    /// then removes the label from the unpatched table.
    /// </summary>
    private void PatchLabel(Label label)
    {
        if (!_unpatchedJumps.TryGetValue(label, out var sites))
            return;

        var target = _instructions.Count;
        foreach (var site in sites)
        {
            var old = _instructions[site];
            _instructions[site] = new Instruction(old.Kind, intOperand: target);
        }

        _unpatchedJumps.Remove(label);
    }

    /// <summary>Emit an instruction.</summary>
    private void Emit(Instruction instruction) => _instructions.Add(instruction);

    /// <summary>Adds a new constant.</summary>
    private int AddConstant(Constant constant) => _constantPool.Add(constant);

    private void VisitForStatement(ForStatement forStatement)
    {
        _locals.EnterScope();

        if (forStatement.Iterator is not null)
            Visit(forStatement.Iterator);

        var loopStartLabel = NewLabel();
        var loopEndLabel = NewLabel();

        EmitJump(loopEndLabel);  // Jump to condition check first (condition may be absent, in which case it defaults to true)
        PatchLabel(loopStartLabel);  // Loop body starts here

        Visit(forStatement.Body);

        if (forStatement.Step is not null)
            Visit(forStatement.Step);

        EmitJump(loopStartLabel);  // Jump back to the start of the loop

        PatchLabel(loopEndLabel);  // Loop ends here

        _locals.ExitScope();
    }

    // TODO: Test scope management here
    private void VisitIfStatement(IfStatement ifStatement)
    {
        _locals.EnterScope();

        // Evaluate the condition — leaves a bool on the stack.
        Visit(ifStatement.Expr);

        var elseLabel = NewLabel();
        EmitJumpIfFalse(elseLabel);   // jump past the then-branch if condition is false

        Visit(ifStatement.Stmt);      // then-branch

        if (ifStatement.ElsePart is not null)
        {
            var endLabel = NewLabel();
            EmitJump(endLabel);        // jump past else-branch after then-branch executes
            PatchLabel(elseLabel);     // else-branch starts here
            Visit(ifStatement.ElsePart);
            PatchLabel(endLabel);      // end of if/else
        }
        else
        {
            PatchLabel(elseLabel);     // no else: target lands right after then-branch
        }

        _locals.ExitScope();
    }

    private void VisitVariableDeclaration(VariableDeclaration variableDeclaration)
    {
        foreach (var declaration in variableDeclaration.Declarations)
        {
            if (declaration.VarName is not IdentifierNode varName)
                throw BytecodeError.ExpectedIdentifierInVariableDeclaration();

            var localKind = variableDeclaration.Kind switch
            {
                "var" => LocalKind.Var,
                "const" => LocalKind.Const,
                _ => LocalKind.Let,
            };

            var type = declaration.VarType is IdentifierNode varType
                ? VarTypeExtensions.Parse(varType.Name)
                : VarType.Unknown;

            if (declaration.Init is not null)
            {
                // Emit code to evaluate the initializer so the value is on the stack, then store it.
                Visit(declaration.Init);
                Emit(new Instruction(InstructionKind.StoreVar, intOperand: _locals.GetOrCreateLocal(varName.Name, localKind, type).Id));
            }
            else
            {
                // Type-annotated declaration with no initializer: register the local but emit no instructions.
                _locals.GetOrCreateLocal(varName.Name, localKind, type);
            }
        }
    }

    private void VisitBinaryExpression(BinaryExpression binaryExpression)
    {
        Visit(binaryExpression.Left);   // Evaluate left side
        Visit(binaryExpression.Right);  // Evaluate right side

        var kind = binaryExpression.Operator switch
        {
            "+" => InstructionKind.Add,
            "-" => InstructionKind.Sub,
            "*" => InstructionKind.Mul,
            "/" => InstructionKind.Div,
            "%" => InstructionKind.Mod,
            "==" => InstructionKind.Eq,
            "!=" => InstructionKind.Neq,
            "<" => InstructionKind.Lt,
            ">" => InstructionKind.Gt,
            "<=" => InstructionKind.Leq,
            ">=" => InstructionKind.Geq,
            _ => throw BytecodeError.UnsupportedOperator(binaryExpression.Operator)
        };

        Emit(new Instruction(kind));    // Emit the operator instruction, which will consume the two operands from the stack
    }
}