using Lumi.Ast;
using Lumi.Bytecode.Constants;
using Lumi.Bytecode.Instructions;
using Lumi.Bytecode.Jumps;

namespace Lumi.Bytecode;

/// <summary>
/// Generates bytecode instructions and manages constants for a given abstract syntax tree (AST).
/// </summary>
public sealed class BytecodeGenerator
{
    private readonly List<Instruction> _instructions = [];
    private readonly ConstantPool _constantPool = new();
    private readonly Dictionary<Label, int> _labelPositions = [];
    private readonly Dictionary<Label, int> _symbolTable = [];
    private readonly Dictionary<Label, List<PendingJump>> _unpatchedJumps = [];
    private readonly Dictionary<string, Label> _localVariables = [];
    private int _nextLabelId = 0;

    public IReadOnlyList<Instruction> Instructions => _instructions;
    public IReadOnlyList<Constant> Constants => _constantPool.Values;

    /// <summary>
    /// Generates a bytecode result by traversing the specified syntax node.
    /// </summary>
    /// <param name="node">The root node of the syntax tree to generate bytecode from. Cannot be null.</param>
    /// <returns>A <see cref="BytecodeResult"/> containing the generated bytecode for the provided syntax node.</returns>
    public BytecodeResult Generate(Node node)
    {
        Visit(node);
        return BytecodeResult.FromGenerator(this);
    }

    private Label GetOrCreateLocal(string name)
    {
        if (_localVariables.TryGetValue(name, out var local))
            return local;
        else
        {
            var newLabel = new Label(_nextLabelId++);
            _localVariables[name] = newLabel;
            return newLabel;
        }
    }

    private void Visit(Node node)
    {
        if (node is Program program)
        {
            for (int i = 0; i < program.Body.Count; i++)
            {
                Visit(program.Body[i]);
            }
        }

        if (node is VariableDeclaration variableDeclaration)
        {
            foreach (var declaration in variableDeclaration.Declarations)
            {
                if (declaration.VarName is IdentifierNode varName) // Else throw exception?
                {
                    // TODO: implement this as well
                    //if (variableDeclaration.Kind == "var")
                    //{
                    //    _localVariables[varName.Name] = new Label($"var_{varName.Name}");
                    //}
                    //else if (variableDeclaration.Kind == "let")
                    //{
                    //    _localVariables[varName.Name] = new Label($"let_{varName.Name}");
                    //}
                    //else if (variableDeclaration.Kind == "const")
                    //{
                    //    _localVariables[varName.Name] = new Label($"const_{varName.Name}");
                    //}

                    if (declaration.Init is not null)
                    {
                        Visit(declaration.Init);
                        var idx = GetOrCreateLocal(varName.Name);
                        Emit(new Instruction(InstructionKind.StoreVar, intOperand: idx.Id));
                    }
                    else
                    {

                    }
                }
            }
        }

        if (node is PrintStatement printStatement)
        {
            Visit(printStatement.Argument);
            Emit(new Instruction(InstructionKind.Print));
        }

        if (node is NumberNode number)
        {
            var idx = AddConstant(Constant.FromNumber(number.Value));
            Emit(new Instruction(InstructionKind.PushConst, intOperand: idx));
        }

        if (node is StringNode str)
        {
            var idx = AddConstant(Constant.FromString(str.Value));
            Emit(new Instruction(InstructionKind.PushConst, intOperand: idx));
        }

        if (node is ExpressionStatement expressionStatement)
        {
            Visit(expressionStatement.Expression);
        }

        if (node is BinaryExpression binaryExpression)
        {
            Visit(binaryExpression.Left);
            Visit(binaryExpression.Right);
            switch (binaryExpression.Operator)
            {
                case "+":
                    Emit(new Instruction(InstructionKind.Add));
                    break;
                case "-":
                    Emit(new Instruction(InstructionKind.Sub));
                    break;
                case "*":
                    Emit(new Instruction(InstructionKind.Mul));
                    break;
                case "/":
                    Emit(new Instruction(InstructionKind.Div));
                    break;
                default:
                    throw BytecodeError.UnsupportedOperator(binaryExpression.Operator);
            }
        }
    }

    private void Emit(Instruction instruction)
    {
        _instructions.Add(instruction);
    }

    private int AddConstant(Constant constant) => _constantPool.Add(constant);
}