using Lumi.AST;
using Lumi.Bytecode.Constants;
using Lumi.Bytecode.Instructions;
using Lumi.Bytecode.Locals;
using Lumi.Language;

namespace Lumi.Bytecode;

/// <summary>
/// Generates bytecode instructions and manages constants for a given abstract syntax tree (AST).
/// </summary>
public sealed class BytecodeGenerator
{
    private readonly List<Instruction> _instructions = new(capacity: 64);
    private readonly ConstantPool _constantPool = new();
    private readonly Dictionary<Label, List<int>> _unpatchedJumps = [];
    private readonly Dictionary<string, int> _functionAddresses = [];
    private readonly Dictionary<string, IReadOnlyList<string>> _structDefinitions = new(StringComparer.Ordinal);
    private readonly Dictionary<string, Dictionary<string, int>> _structMethodAddresses = new(StringComparer.Ordinal);
    private readonly LocalManager _locals = new();
    private int _nextLabelId = 0;

    public IReadOnlyList<Instruction> Instructions => _instructions;
    public IReadOnlyList<Constant> Constants => _constantPool.Values;
    public IReadOnlyList<Local> Locals => _locals.AllLocals;
    public IReadOnlyDictionary<string, int> FunctionAddresses => _functionAddresses;
    public IReadOnlyDictionary<string, IReadOnlyList<string>> StructDefinitions => _structDefinitions;
    public IReadOnlyDictionary<string, IReadOnlyDictionary<string, int>> StructMethodAddresses 
        => _structMethodAddresses.ToDictionary(static kvp => kvp.Key, static kvp => (IReadOnlyDictionary<string, int>)kvp.Value, StringComparer.Ordinal);

    public BytecodeGenerator()
    {
        _locals.EnterScope();
    }

    /// <summary>
    /// Generates a bytecode result by traversing the specified syntax node.
    /// </summary>
    /// <param name="node">The root node of the syntax tree to generate bytecode from. Cannot be null.</param>
    /// <returns>A <see cref="BytecodeResult"/> containing the generated bytecode for the provided syntax node.</returns>
    public BytecodeResult Generate(Node node)
    {
        Visit(node);

        return BytecodeResult.FromGenerator(this);
    }

    private void Visit(Node node)
    {
        switch (node)
        {
            case Program program:
                PreRegisterStructDeclarations(program);

                for (int i = 0; i < program.Body.Count; i++)
                    Visit(program.Body[i]);
                break;

            case BlockStatement block:
                _locals.EnterScope();
                foreach (var stmt in block.Body)
                    Visit(stmt);
                _locals.ExitScope();
                break;

            case VariableDeclaration variableDeclaration:
                VisitVariableDeclaration(variableDeclaration);
                break;

            case FunctionDeclaration functionDeclaration:
                VisitFunctionDeclaration(functionDeclaration);
                break;

            case StructDeclaration structDeclaration:
                VisitStructDeclaration(structDeclaration);
                break;

            case CallExpression callExpression:
                VisitCallExpression(callExpression);
                break;

            case IdentifierNode identifier:
                var local = _locals.LookupLocal(identifier.Name) ?? throw BytecodeError.UndefinedVariable(identifier.Name);
                Emit(Instruction.LoadVar(local.Label));
                break;

            case NewExpression newExpression:
                VisitNewExpression(newExpression);
                break;

            case MemberExpression memberExpression:
                VisitMemberExpression(memberExpression);
                break;

            case PrintStatement printStatement:
                Visit(printStatement.Argument);
                Emit(new Instruction(InstructionKind.Print));
                break;

            case IfStatement ifStatement:
                VisitIfStatement(ifStatement);
                break;

            case ForStatement forStatement:
                VisitForStatement(forStatement);
                break;

            case ReturnStatement returnStatement:
                VisitReturnStatement(returnStatement);
                break;

            case NumberNode number:
                Emit(Instruction.PushConst(AddConstant(Constant.FromNumber(number.Value))));
                break;

            case BooleanNode boolean:
                Emit(Instruction.PushConst(AddConstant(Constant.FromBoolean(boolean.Value))));
                break;

            case StringNode str:
                Emit(Instruction.PushConst(AddConstant(Constant.FromString(str.Value))));
                break;

            case ArrayLiteral arrayLiteral:
                VisitArrayLiteral(arrayLiteral);
                break;

            case IndexExpression indexExpression:
                Visit(indexExpression.Object);
                Visit(indexExpression.Index);
                Emit(Instruction.IndexArray());
                break;

            case ExpressionStatement expressionStatement:
                Visit(expressionStatement.Expression);
                break;

            case UnaryExpression unaryExpression:
                VisitUnaryExpression(unaryExpression);
                break;

            case BinaryExpression binaryExpression:
                VisitBinaryExpression(binaryExpression);
                break;
            case AssignmentExpression assignmentExpression:
                // Target is a variable (e.g. x = value)
                if (assignmentExpression.Left is IdentifierNode targetIdentifier)
                {
                    Visit(assignmentExpression.Right);
                    var targetLocal = _locals.LookupLocal(targetIdentifier.Name) ?? throw BytecodeError.UndefinedVariable(targetIdentifier.Name);
                    Emit(Instruction.StoreVar(targetLocal.Label));
                    break;
                }

                // Target is a struct field (e.g. myStruct.field = value)
                if (assignmentExpression.Left is MemberExpression memberAssignment)
                {
                    Visit(memberAssignment.Object);
                    Visit(assignmentExpression.Right);
                    Emit(Instruction.StoreField(memberAssignment.Property.Name));
                    break;
                }

                throw BytecodeError.InvalidAssignmentTarget();

            default:
                break;
        }
    }

    private void PreRegisterStructDeclarations(Program program)
    {
        foreach (var statement in program.Body)
        {
            if (statement is not StructDeclaration structDeclaration)
                continue;

            var structName = structDeclaration.Name.Name;
            if (_structDefinitions.ContainsKey(structName))
                throw BytecodeError.StructAlreadyDefined(structName);

            var fields = structDeclaration.Fields.Select(static f => f.Name.Name).ToArray();
            _structDefinitions[structName] = fields;
            _structMethodAddresses[structName] = new Dictionary<string, int>(StringComparer.Ordinal);
        }
    }

    /// <summary>Allocates a fresh jump label whose target will be resolved later via <see cref="PatchLabel"/>.</summary>
    private Label NewLabel() => new(_nextLabelId++);

    /// <summary>Emits an unconditional jump to <paramref name="target"/>, recording it for back-patching.</summary>
    private void EmitJump(Label target)
    {
        _unpatchedJumps.TryAdd(target, []);
        _unpatchedJumps[target].Add(_instructions.Count);
        Emit(Instruction.Jump(0));
    }

    /// <summary>Emits a conditional jump that jumps to <paramref name="target"/> when the top-of-stack is false.</summary>
    private void EmitJumpIfFalse(Label target)
    {
        _unpatchedJumps.TryAdd(target, []);
        _unpatchedJumps[target].Add(_instructions.Count);
        Emit(Instruction.JumpIfFalse(0));
    }

    /// <summary>
    /// Resolves all jumps that target <paramref name="label"/> to point at the current instruction position,
    /// then removes the label from the unpatched table.
    /// </summary>
    private void PatchLabel(Label label)
    {
        if (!_unpatchedJumps.TryGetValue(label, out var sites))
            return;

        var target = _instructions.Count;
        foreach (var site in sites)
        {
            var old = _instructions[site];
            _instructions[site] = new Instruction(old.Kind, intOperand: target);
        }

        _unpatchedJumps.Remove(label);
    }

    /// <summary>Emit an instruction.</summary>
    private void Emit(Instruction instruction) => _instructions.Add(instruction);

    /// <summary>Adds a new constant.</summary>
    private int AddConstant(Constant constant) => _constantPool.Add(constant);

    private void VisitForStatement(ForStatement forStatement)
    {
        _locals.EnterScope();

        if (forStatement.Iterator is null)
            throw BytecodeError.ForStatementMissingIterator();

        if (forStatement.Iterator is not IdentifierNode)
            throw BytecodeError.NoValidIteratorFound();

        var iteratorName = ((IdentifierNode)forStatement.Iterator).Name;
        var varIdx = _locals.GetOrCreateLocal(iteratorName, LocalKind.Var, VarType.Int);

        // Store the start value into the iterator variable.
        Visit(forStatement.Start);
        Emit(Instruction.StoreVar(varIdx));

        // Store the end bound in a hidden local.
        var endIdx = _locals.GetOrCreateLocal("$end", LocalKind.Let, VarType.Int);
        Visit(forStatement.End);
        Emit(Instruction.StoreVar(endIdx));

        // Store the step value in a hidden local (defaults to 1).
        var stepIdx = _locals.GetOrCreateLocal("$step", LocalKind.Let, VarType.Int);
        if (forStatement.Step is not null)
        {
            Visit(forStatement.Step);
        }
        else
        {
            Emit(Instruction.PushConst(AddConstant(Constant.FromNumber(1))));
        }
        Emit(Instruction.StoreVar(stepIdx));

        // Record the loop-header position for the backward jump.
        var loopStart = _instructions.Count;
        var endLabel = NewLabel();

        // Condition: iterator <= end
        Emit(Instruction.LoadVar(varIdx));
        Emit(Instruction.LoadVar(endIdx));
        Emit(new Instruction(InstructionKind.Leq));

        EmitJumpIfFalse(endLabel);

        // Body
        Visit(forStatement.Body);

        // Increment: iterator = iterator + step
        Emit(Instruction.LoadVar(varIdx));
        Emit(Instruction.LoadVar(stepIdx));
        Emit(Instruction.Add());
        Emit(Instruction.StoreVar(varIdx));

        // Jump back to condition check.
        Emit(Instruction.Jump(loopStart));
        PatchLabel(endLabel);

        _locals.ExitScope();
    }

    // TODO: Test scope management here
    private void VisitIfStatement(IfStatement ifStatement)
    {
        _locals.EnterScope();

        // Evaluate the condition — leaves a bool on the stack.
        Visit(ifStatement.Expr);

        var elseLabel = NewLabel();
        EmitJumpIfFalse(elseLabel);   // jump past the then-branch if condition is false

        Visit(ifStatement.Stmt);      // then-branch

        if (ifStatement.ElsePart is not null)
        {
            var endLabel = NewLabel();
            EmitJump(endLabel);        // jump past else-branch after then-branch executes
            PatchLabel(elseLabel);     // else-branch starts here
            Visit(ifStatement.ElsePart);
            PatchLabel(endLabel);      // end of if/else
        }
        else
        {
            PatchLabel(elseLabel);     // no else: target lands right after then-branch
        }

        _locals.ExitScope();
    }

    private void VisitArrayLiteral(ArrayLiteral arrayLiteral)
    {
        foreach (var element in arrayLiteral.Elements)
        {
            Visit(element);
        }

        Emit(Instruction.MakeArray(arrayLiteral.Elements.Count));
    }

    private void VisitVariableDeclaration(VariableDeclaration variableDeclaration)
    {
        foreach (var declaration in variableDeclaration.Declarations)
        {
            if (declaration.VarName is not IdentifierNode varName)
                throw BytecodeError.ExpectedIdentifierInVariableDeclaration();

            var localKind = variableDeclaration.Kind switch
            {
                "var" => LocalKind.Var,
                "const" => LocalKind.Const,
                _ => LocalKind.Let,
            };

            var type = declaration.VarType is IdentifierNode varType
                ? VarTypeExtensions.Parse(varType.Name)
                : VarType.Unknown;

            if (declaration.Init is not null)
            {
                // Emit code to evaluate the initializer so the value is on the stack, then store it.
                Visit(declaration.Init);
                Emit(Instruction.StoreVar(_locals.GetOrCreateLocal(varName.Name, localKind, type)));
            }
            else
            {
                // Type-annotated declaration with no initializer: register the local but emit no instructions.
                _locals.GetOrCreateLocal(varName.Name, localKind, type);
            }
        }
    }

    private void VisitUnaryExpression(UnaryExpression unaryExpression)
    {
        Visit(unaryExpression.Argument);

        var kind = unaryExpression.Operator switch
        {
            "-" => InstructionKind.Negate,
            "!" => InstructionKind.Not,
            _ => throw BytecodeError.UnsupportedOperator(unaryExpression.Operator)
        };

        Emit(new Instruction(kind));
    }

    private void VisitBinaryExpression(BinaryExpression binaryExpression)
    {
        Visit(binaryExpression.Left);   // Evaluate left side
        Visit(binaryExpression.Right);  // Evaluate right side

        var kind = binaryExpression.Operator switch
        {
            "+" => InstructionKind.Add,
            "-" => InstructionKind.Sub,
            "*" => InstructionKind.Mul,
            "/" => InstructionKind.Div,
            "%" => InstructionKind.Mod,
            "==" => InstructionKind.Eq,
            "!=" => InstructionKind.Neq,
            "<" => InstructionKind.Lt,
            ">" => InstructionKind.Gt,
            "<=" => InstructionKind.Leq,
            ">=" => InstructionKind.Geq,
            _ => throw BytecodeError.UnsupportedOperator(binaryExpression.Operator)
        };

        Emit(new Instruction(kind));    // Emit the operator instruction, which will consume the two operands from the stack
    }

    private void VisitFunctionDeclaration(FunctionDeclaration functionDeclaration)
    {
        if (functionDeclaration.Id is not IdentifierNode functionName)
            throw BytecodeError.ExpectedIdentifierInFunctionDeclaration();

        VisitFunctionBody(functionDeclaration, static (generator, name, address) => generator._functionAddresses[name] = address, functionName.Name, receiverLocalName: null);
    }

    private void VisitFunctionBody(
        FunctionDeclaration functionDeclaration,
        Action<BytecodeGenerator, string, int> registerEntryPoint,
        string entryName,
        string? receiverLocalName)
    {
        // Jump over the function body so it isn't executed during normal program flow.
        var skipLabel = NewLabel();
        EmitJump(skipLabel);

        // Record the function entry point (the instruction right after the jump).
        registerEntryPoint(this, entryName, _instructions.Count);

        // Reset the slot counter so function-local variables are numbered from 0,
        // relative to the function's base pointer at runtime.
        var savedSlotCounter = _locals.SaveAndResetSlotCounter();

        // Create a new scope for the function body.
        _locals.EnterScope();

        // Register parameters as locals and emit StoreVar instructions
        // to pop the caller's arguments into them.
        // Arguments are pushed left-to-right, so we pop right-to-left.
        var parameterLabels = new List<Label>(functionDeclaration.Params.Count);
        if (receiverLocalName is not null)
            parameterLabels.Add(_locals.GetOrCreateLocal(receiverLocalName, LocalKind.Let, VarType.Unknown));

        foreach (var param in functionDeclaration.Params)
        {
            if (param is not IdentifierNode paramName)
                throw BytecodeError.ExpectedIdentifierInFunctionParameter();

            parameterLabels.Add(_locals.GetOrCreateLocal(paramName.Name, LocalKind.Var, VarType.Unknown));
        }

        for (int i = parameterLabels.Count - 1; i >= 0; i--)
        {
            Emit(Instruction.StoreVar(parameterLabels[i]));
        }

        // Generate bytecode for the function body.
        Visit(functionDeclaration.Body);

        // Implicit return: push undefined and return.
        Emit(Instruction.PushConst(AddConstant(Constant.Undefined())));
        Emit(new Instruction(InstructionKind.Return));

        _locals.ExitScope();

        // Restore the global slot counter so outer-scope numbering resumes correctly.
        _locals.RestoreSlotCounter(savedSlotCounter);

        // Patch the skip-jump so normal execution resumes here.
        PatchLabel(skipLabel);
    }

    private void VisitCallExpression(CallExpression callExpression)
    {
        if (callExpression.Callee is IdentifierNode functionName)
        {
            // Push arguments left-to-right.
            foreach (var arg in callExpression.Arguments)
            {
                Visit(arg);
            }

            // Emit the call.
            Emit(new Instruction(InstructionKind.CallFn, functionName.Name));
            return;
        }

        if (callExpression.Callee is not MemberExpression memberExpression)
            throw BytecodeError.ExpectedIdentifierInFunctionCall();

        if (memberExpression.Property is not IdentifierNode methodIdentifier)
            throw BytecodeError.ExpectedIdentifierInMemberAccess();

        // First push object
        // Then push any arguments left to right
        // Then push the call instruction
        Visit(memberExpression.Object);

        foreach (var arg in callExpression.Arguments)
        {
            Visit(arg);
        }

        Emit(Instruction.CallMemberMethod(methodIdentifier.Name, callExpression.Arguments.Count));
    }

    private void VisitStructDeclaration(StructDeclaration structDeclaration)
    {
        var structName = structDeclaration.Name.Name;
        if (!_structDefinitions.ContainsKey(structName))
            _structDefinitions[structName] = [.. structDeclaration.Fields.Select(static f => f.Name.Name)];

        _structMethodAddresses.TryAdd(structName, new Dictionary<string, int>(StringComparer.Ordinal));

        foreach (var method in structDeclaration.Methods)
        {
            if (method.Id is not IdentifierNode methodName)
                throw BytecodeError.ExpectedIdentifierInFunctionDeclaration();

            // The method body will be emitted as a regular function, but we register its entry point in the _structMethodAddresses table
            // so it can be called via CallMemberMethod instructions.
            VisitFunctionBody(
                method,
                static (generator, entryName, address) =>
                {
                    var separatorIndex = entryName.IndexOf('.', StringComparison.Ordinal);
                    var structName = entryName[..separatorIndex];
                    var methodName = entryName[(separatorIndex + 1)..];
                    generator._structMethodAddresses[structName][methodName] = address;
                },
                $"{structName}.{methodName.Name}",
                receiverLocalName: "this");
        }
    }

    private void VisitNewExpression(NewExpression newExpression)
    {
        var structName = newExpression.TypeName.Name;
        if (!_structDefinitions.ContainsKey(structName))
            throw BytecodeError.UndefinedStruct(structName);

        foreach (var argument in newExpression.Arguments)
            Visit(argument);

        Emit(Instruction.NewStruct(structName, newExpression.Arguments.Count));
    }

    private void VisitMemberExpression(MemberExpression memberExpression)
    {
        Visit(memberExpression.Object);
        Emit(Instruction.LoadField(memberExpression.Property.Name));
    }

    private void VisitReturnStatement(ReturnStatement returnStatement)
    {
        // If there's a return value, evaluate it and leave it on the stack.
        if (returnStatement.Argument != null)
        {
            Visit(returnStatement.Argument);
        }
        else
        {
            // No explicit return value: push undefined
            Emit(Instruction.PushConst(AddConstant(Constant.Undefined())));
        }

        // Emit the return instruction
        Emit(new Instruction(InstructionKind.Return));
    }
}
